#!/bin/zsh
tmpfile=/tmp/test #$(mktemp)
export | grep -oP '^.*?(?=\=)' > $tmpfile
nvidia-docker run --privileged --network=host --pid=host -v /dev:/dev -v /tmp:/tmp -v /var/tmp:/var/tmp -v $HOME:$HOME -v /etc/group:/etc/group:ro -v /etc/shadow:/etc/shadow:ro -v /etc/passwd:/etc/passwd:ro -v /etc/localtime:/etc/localtime:ro -v /run:/run -v /mnt:/mnt -u $(id -u) --env-file $tmpfile zasdfgbnmsystem/desktop
rm $tmpfile
